services:
  - type: web
    name: robot-heart
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.18.0
      - key: PORT
        value: 3001
